### ISSUE TITLE
Laravel 8, PHP 8 support?

### ISSUE THREAD

**Issue by rosen91** [miracuthbert/laravel-royalty#1]
Do you have plans for supporting Laravel 8 and PHP8? Should be a simple change in composer deps, otherwize i might have time to send a pull-request in the weekend for this.

**Comment by usernotnull** [comment]
PR made: https://github.com/miracuthbert/laravel-royalty/pull/2

**Comment by gogl92** [comment]
@rosen91 this can be closed now, with the latest PR I updated the project up to Laravel 10

**Comment by miracuthbert** [comment]
Thanks @rosen91 for raising this. Sorry for the late response. 

As mentioned by @gogl92 the project is now updated to support all the way to Laravel 10.
